DROP TABLE mesh4 CASCADE;

CREATE TABLE mesh4 (
  "MESH_CODE" TEXT,
  "HTKSYORI" TEXT,
  "HTKSAKI" TEXT,
  "GASSAN" TEXT,
  "人口総数" NUMERIC,
  "人口総数　男" NUMERIC,
  "人口総数　女" NUMERIC,
  "０〜１４歳人口総数" NUMERIC,
  "０〜１４歳人口　男" NUMERIC,
  "０〜１４歳人口　女" NUMERIC,
  "１５歳以上人口総数" NUMERIC,
  "１５歳以上人口　男" NUMERIC,
  "１５歳以上人口　女" NUMERIC,
  "１５〜６４歳人口総数" NUMERIC,
  "１５〜６４歳人口　男" NUMERIC,
  "１５〜６４歳人口　女" NUMERIC,
  "２０歳以上人口総数" NUMERIC,
  "２０歳以上人口　男" NUMERIC,
  "２０歳以上人口　女" NUMERIC,
  "６５歳以上人口総数" NUMERIC,
  "６５歳以上人口　男" NUMERIC,
  "６５歳以上人口　女" NUMERIC,
  "７５歳以上人口総数" NUMERIC,
  "７５歳以上人口　男" NUMERIC,
  "７５歳以上人口　女" NUMERIC,
  "外国人人口総数" NUMERIC,
  "外国人人口　男" NUMERIC,
  "外国人人口　女" NUMERIC,
  "世帯総数" NUMERIC,
  "一般世帯数" NUMERIC,
  "１人世帯の一般世帯数" NUMERIC,
  "２人世帯の一般世帯数" NUMERIC,
  "３人世帯の一般世帯数" NUMERIC,
  "４人世帯の一般世帯数" NUMERIC,
  "５人世帯の一般世帯数" NUMERIC,
  "６人世帯の一般世帯数" NUMERIC,
  "７人以上世帯の一般世帯数" NUMERIC,
  "親族のみの一般世帯数" NUMERIC,
  "核家族の一般世帯数" NUMERIC,
  "核家族以外の一般世帯数" NUMERIC,
  "６歳未満世帯員のいる一般世帯数" NUMERIC,
  "６５歳以上世帯員のいる一般世帯数" NUMERIC,
  "世帯主の年齢が２０〜２９歳の１人世帯の一般世帯数" NUMERIC,
  "高齢単身の一般世帯数" NUMERIC,
  "高齢夫婦のみの一般世帯数" NUMERIC
);
